146c146
<         git checkout -t $$i ; done
---
> 	 git checkout -t $$i ; done
173,175c173,175
<         '/^# File/,/^# Finished Make data base/ {if ($$1 !~ "^[#.]") {print $$1}}'\
<         | sort | egrep -v -e '^[^[:alnum:]]' -e '^$@$$' | xargs | tr ' ' '\n' | awk\
<         '{print "    - "$$0}' | less  # http://stackoverflow.com/a/26339924
---
> 	 '/^# File/,/^# Finished Make data base/ {if ($$1 !~ "^[#.]") {print $$1}}'\
> 	 | sort | egrep -v -e '^[^[:alnum:]]' -e '^$@$$' | xargs | tr ' ' '\n' | awk\
> 	 '{print "    - "$$0}' | less  # http://stackoverflow.com/a/26339924
325a326,347
> 
> # aclarknet-database
> APP=database
> PROJECT=aclarknet
> heroku-remote:
> 	git remote add heroku git@heroku.com:aclarknet-database.git
> heroku-remote2:
> 	git remote add heroku git@heroku.com:aclarknet-database2.git
> patch:
> 	diff ~/Developer/project-makefile/Makefile Makefile > makefile.patch
> pg-capture:
> 	heroku pg:backups capture
> pg-copy:
> 	heroku maintenance:on
> 	heroku ps:scale web=0
> 	heroku pg:copy DATABASE_URL `heroku config:get DATABASE_URL2`
> 	heroku ps:scale web=1
> 	heroku maintenance:off
> pg-reset:
> 	heroku pg:reset DATABASE_URL --confirm aclarknet-database2
> pg-restore:
> 	pg_restore -c -d aclarknet ~/Dropbox/Documents/ACLARKNET/aclarknet-database.dump
