86c86
< db: django-clean-db django-init-db
---
> db: django-database
88,97c88,90
< django-clean: django-clean-db django-clean-proj  # Chain
< django-clean-db: django-clean-sql  # Alias
< django-init: django-init-db django-init-proj  # Chain
< django-init-db: django-init-sql  # Alias
< django-clean-pg:  # PostgreSQL
< 	-dropdb $(PROJECT)
< django-clean-proj:
< 	@-rm -rvf $(PROJECT)
< 	@-rm -v manage.py
< django-clean-sql:  # SQLite
---
> django-clean:  # SQLite or PostgreSQL
> 	-rm -rf $(PROJECT)
> 	-rm manage.py
99c92,94
< django-init-pg:  # PostgreSQL
---
> 	-dropdb $(PROJECT)
> django-database:
> 	-touch db.sqlite3
101c96
< django-init-proj:
---
> django-init:
105,106d99
< django-init-sql:  # SQLite
< 	-touch db.sqlite3
325a319,340
> 
> # aclarknet-database
> APP=database
> PROJECT=aclarknet
> heroku-remote:
> 	git remote add heroku git@heroku.com:aclarknet-database.git
> heroku-remote2:
> 	git remote add heroku git@heroku.com:aclarknet-database2.git
> patch:
> 	diff ~/Developer/project-makefile/Makefile Makefile > makefile.patch
> pg-capture:
> 	heroku pg:backups capture
> pg-copy:
> 	heroku maintenance:on
> 	heroku ps:scale web=0
> 	heroku pg:copy DATABASE_URL `heroku config:get DATABASE_URL2`
> 	heroku ps:scale web=1
> 	heroku maintenance:off
> pg-reset:
> 	heroku pg:reset DATABASE_URL --confirm aclarknet-database2
> pg-restore:
> 	pg_restore -c -d aclarknet ~/Dropbox/Documents/ACLARKNET/aclarknet-database.dump
