# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='issue_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name=b'Issue Date'),
        ),
    ]
