# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20170810_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='database.Contact'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='database.Contact'),
        ),
        migrations.AlterField(
            model_name='report',
            name='invoices',
            field=models.ManyToManyField(blank=True, to='database.Invoice'),
        ),
    ]
