# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20170817_0545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='editor_choices',
            new_name='editor',
        ),
    ]
