# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_profile_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
