# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_profile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('gross', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('net', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
