# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
