# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_client_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notify',
            field=models.BooleanField(default=True),
        ),
    ]
