# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_profile_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
