# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_task_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(blank=True, default=b'white', max_length=7, null=True),
        ),
    ]
