# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_choices',
            field=models.CharField(blank=True, choices=[('paypal', 'PayPal'), ('check', 'Check')], max_length=255, null=True, verbose_name='Preferred Payment Method'),
        ),
    ]
