# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-15 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_auto_20160507_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
