# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_auto_20161020_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='currency_symbol',
            field=models.CharField(blank=True, default='$', max_length=300, null=True, verbose_name='Currency Symbol'),
        ),
        migrations.AlterField(
            model_name='company',
            name='estimate_counter',
            field=models.IntegerField(blank=True, null=True, verbose_name='Estimate Counter'),
        ),
        migrations.AlterField(
            model_name='company',
            name='invoice_counter',
            field=models.IntegerField(blank=True, null=True, verbose_name='Invoice Counter'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Estimate Amount'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='currency',
            field=models.CharField(blank=True, default='United States Dollar - USD', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='document_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Estimate ID'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='issue_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Issue Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Invoice Amount'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(blank=True, default='United States Dollar - USD', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency_symbol',
            field=models.CharField(blank=True, default='$', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='document_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Invoice ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Issue Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='po_number',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='PO Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='unit',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=12, null=True, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Project Code'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(blank=True, default='white', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='unit',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=12, null=True, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='issue_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Issue Date'),
        ),
        migrations.AlterField(
            model_name='time',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=12, null=True, verbose_name='Hours'),
        ),
    ]
