# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_project_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
