# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_auto_20170825_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='database.Contact'),
        ),
    ]
