# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_auto_20161207_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
