# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_estimate_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='estimate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='times', to='database.Estimate'),
        ),
    ]
