# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='icon',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
