# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 11:28
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_auto_20170826_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='dashboard_choices',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('invoices', 'Invoices'), ('notes', 'Notes'), ('plot', 'Plot'), ('projects', 'Projects'), ('times', 'Times'), ('totals', 'Totals')], max_length=41, null=True, verbose_name='Dashboard Choices'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dashboard_choices',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('invoices', 'Invoices'), ('notes', 'Notes'), ('plot', 'Plot'), ('projects', 'Projects'), ('times', 'Times'), ('totals', 'Totals')], max_length=41, null=True, verbose_name='Dashboard Choices'),
        ),
    ]
