# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-13 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0026_client_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
