# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_company_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
