# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-25 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0028_client_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
