# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-25 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0029_testimonial_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
