# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0031_dashboarditem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractsettings',
            options={'verbose_name_plural': 'Contract settings'},
        ),
    ]
