# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0032_auto_20170209_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
