# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0033_note_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
