# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0034_note_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='requires',
            field=models.ManyToManyField(blank=True, related_name='Requires', to='database.Note'),
        ),
    ]
