# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0035_note_requires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
