# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0035_remove_invoice_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='doc_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Doc ID'),
        ),
    ]
