# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 14:51
from __future__ import unicode_literals

from django.db import migrations

#import tinymce.models


class Migration(migrations.Migration):
    """
    """

    dependencies = [
        ('database', '0036_auto_20170605_1803'),
    ]

#    operations = [
#        migrations.AlterField(
#            model_name='note',
#            name='note',
#            field=tinymce.models.HTMLField(blank=True, null=True),
#        ),
#    ]
