# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0038_auto_20170902_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysettings',
            name='estimate_counter',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='invoice_counter',
        ),
    ]
