# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0038_auto_20170606_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
