# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0039_contact_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='uuid',
            field=models.CharField(default=uuid.UUID('7d7b454c-0073-4079-8ade-bd3a6430c0cb'), max_length=300),
        ),
    ]
