# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0039_auto_20170902_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysettings',
            name='note',
        ),
        migrations.RemoveField(
            model_name='service',
            name='company',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='company',
        ),
        migrations.DeleteModel(
            name='CompanySettings',
        ),
    ]
