# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0040_auto_20170902_1841'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContractSettings',
        ),
    ]
