# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0040_contact_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='uuid',
            field=models.CharField(default=uuid.UUID('cbb425c4-808e-4628-be55-b5767147ffea'), max_length=300, verbose_name='UUID'),
        ),
    ]
