# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0041_delete_contractsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appsettings',
            options={'verbose_name_plural': 'App Settings'},
        ),
    ]
