# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0041_auto_20170608_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='uuid',
            field=models.CharField(default=uuid.UUID('401fcf25-9c92-4c93-b3bd-af059110e3a1'), max_length=300, verbose_name='UUID'),
        ),
    ]
