# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 22:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0043_auto_20170902_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboarditem',
            options={'ordering': ('order',), 'verbose_name_plural': 'Dashboard Items'},
        ),
    ]
