# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0043_auto_20170609_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='uuid',
            field=models.CharField(default=uuid.UUID('e152b87d-fc6a-4a9a-b9bd-0044f76a4005'), max_length=300, verbose_name='UUID'),
        ),
    ]
