# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0044_auto_20170609_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=300, verbose_name='UUID'),
        ),
    ]
