# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0044_auto_20170902_1850'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppSettings',
            new_name='SettingsApp',
        ),
        migrations.AlterModelOptions(
            name='settingsapp',
            options={'verbose_name': 'Settings App'},
        ),
    ]
