# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0045_auto_20170609_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('contacts', models.ManyToManyField(blank=True, related_name='Contacts', to='database.Contact')),
            ],
        ),
    ]
