# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0045_auto_20170903_0656'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('currency_symbol', models.CharField(blank=True, default='$', max_length=300, null=True, verbose_name='Currency Symbol')),
                ('note', models.ManyToManyField(blank=True, to='database.Note')),
            ],
            options={
                'verbose_name': 'Company',
            },
        ),
    ]
