# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0046_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='subject',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
