# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import faker.providers.lorem.la


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0047_auto_20170903_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parties', models.TextField(blank=True, default=faker.providers.lorem.la.Provider.text, null=True, verbose_name='Parties')),
                ('scope_of_work', models.TextField(blank=True, default=faker.providers.lorem.la.Provider.text, null=True, verbose_name='Scope of Work')),
                ('payment_terms', models.TextField(blank=True, default=faker.providers.lorem.la.Provider.text, null=True, verbose_name='Payment Terms')),
                ('timing_of_payment', models.TextField(blank=True, default=faker.providers.lorem.la.Provider.text, null=True, verbose_name='Timing of Payment')),
                ('contributor_assignment_agreement', models.TextField(blank=True, default=faker.providers.lorem.la.Provider.text, null=True, verbose_name='Contributor Assignment Agreement')),
                ('authority_to_act', models.TextField(blank=True, default=faker.providers.lorem.la.Provider.text, null=True, verbose_name='Authority to Act')),
                ('termination', models.TextField(blank=True, default=faker.providers.lorem.la.Provider.text, null=True, verbose_name='Termination')),
                ('governing_laws', models.TextField(blank=True, default=faker.providers.lorem.la.Provider.text, null=True, verbose_name='Governing Laws')),
                ('period_of_agreement', models.TextField(blank=True, default=faker.providers.lorem.la.Provider.text, null=True, verbose_name='Period of Agreement')),
                ('confidentiality', models.TextField(blank=True, default=faker.providers.lorem.la.Provider.text, null=True, verbose_name='Confidentiality')),
                ('taxes', models.TextField(blank=True, default=faker.providers.lorem.la.Provider.text, null=True, verbose_name='Taxes')),
                ('limited_warranty', models.TextField(blank=True, default=faker.providers.lorem.la.Provider.text, null=True, verbose_name='Limited Warranty')),
                ('complete_agreement', models.TextField(blank=True, default=faker.providers.lorem.la.Provider.text, null=True, verbose_name='Complete Agreement')),
            ],
            options={
                'verbose_name': 'Settings Contract',
            },
        ),
    ]
