# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0047_newsletter_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
