# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0048_client_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parties', models.TextField(blank=True, null=True)),
                ('scope_of_work', models.TextField(blank=True, null=True)),
                ('payment_terms', models.TextField(blank=True, null=True)),
                ('timing_of_payment', models.TextField(blank=True, null=True)),
                ('contributor_assignment_agreement', models.TextField(blank=True, null=True)),
                ('authority_to_act', models.TextField(blank=True, null=True)),
                ('termination', models.TextField(blank=True, null=True)),
                ('governing_laws', models.TextField(blank=True, null=True)),
                ('period_of_agreement', models.TextField(blank=True, null=True)),
                ('confidentiality', models.TextField(blank=True, null=True)),
                ('taxes', models.TextField(blank=True, null=True)),
                ('limited_warranty', models.TextField(blank=True, null=True)),
                ('complete_agreement', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='database.Client')),
                ('statement_of_work', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='database.Estimate')),
            ],
        ),
    ]
