# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0053_estimate_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='payment_choices',
            new_name='preferred_payment_method',
        ),
    ]
