# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 12:52
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0056_remove_client_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dashboard_choices',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('estimates', 'Estimates'), ('invoices', 'Invoices'), ('notes', 'Notes'), ('plot', 'Plot'), ('projects', 'Projects'), ('times', 'Times'), ('totals', 'Totals')], max_length=51, null=True, verbose_name='Dashboard Choices'),
        ),
        migrations.AlterField(
            model_name='settingsapp',
            name='dashboard_choices',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('estimates', 'Estimates'), ('invoices', 'Invoices'), ('notes', 'Notes'), ('plot', 'Plot'), ('projects', 'Projects'), ('times', 'Times'), ('totals', 'Totals')], max_length=51, null=True, verbose_name='Dashboard Choices'),
        ),
    ]
