# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0056_auto_20170616_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='period_of_agreement',
        ),
        migrations.RemoveField(
            model_name='contractsettings',
            name='period_of_agreement',
        ),
    ]
