# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0057_auto_20170616_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='authority_to_act',
        ),
        migrations.RemoveField(
            model_name='contractsettings',
            name='authority_to_act',
        ),
    ]
