# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0057_auto_20171025_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='notes',
        ),
        migrations.AddField(
            model_name='report',
            name='cog',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
