# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0058_auto_20171025_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='cog',
        ),
        migrations.RemoveField(
            model_name='report',
            name='cog',
        ),
        migrations.RemoveField(
            model_name='time',
            name='cog',
        ),
    ]
