# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0058_auto_20170616_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contributor_assignment_agreement',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='scope_of_work',
        ),
        migrations.RemoveField(
            model_name='contractsettings',
            name='contributor_assignment_agreement',
        ),
        migrations.RemoveField(
            model_name='contractsettings',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='contractsettings',
            name='scope_of_work',
        ),
    ]
