# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0059_auto_20171027_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='billable_amount',
            new_name='amount',
        ),
    ]
