# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0059_auto_20170616_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Project Name'),
        ),
    ]
