# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-24 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0061_estimate_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='icon_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
