# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0062_report_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dashboard_choices',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('estimates', 'Estimates'), ('invoices', 'Invoices'), ('notes', 'Notes'), ('plot', 'Plot'), ('projects', 'Projects'), ('times', 'Times'), ('totals', 'Totals')], max_length=51, null=True, verbose_name='Dashboard choices'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dashboard_override',
            field=models.BooleanField(default=False, verbose_name='Override Default Dashboard Settings'),
        ),
    ]
