# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-24 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0062_profile_icon_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='page_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='page_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
