# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0065_auto_20171115_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='template_choices',
            field=models.CharField(blank=True, choices=[('html_mail.html', 'Mail'), ('cerberus-fluid.html', 'Fluid'), ('cerberus-hybrid.html', 'Hybrid'), ('cerberus-responsive.html', 'Responsive')], max_length=300, null=True, verbose_name='Template'),
        ),
    ]
