# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0066_auto_20170625_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='override_dashboard',
            field=models.BooleanField(default=False),
        ),
    ]
