# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0066_auto_20171115_0802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail Address'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, verbose_name='Mobile Phone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='office_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, verbose_name='Office Phone'),
        ),
    ]
