# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0067_profile_override_dashboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='requires',
        ),
    ]
