# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0067_auto_20171123_0806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['name']},
        ),
    ]
