# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0068_remove_note_requires'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='complete_agreement',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='confidentiality',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='governing_laws',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='limited_warranty',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='taxes',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='termination',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='timing_of_payment',
        ),
    ]
