# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0069_auto_20170630_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='page_size',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
