# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0071_auto_20170630_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='invoices',
            field=models.ManyToManyField(blank=True, related_name='Invoices', to='database.Invoice'),
        ),
    ]
