# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-02 00:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0073_auto_20170701_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estimate',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
