# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-02 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0076_company_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('pk',)},
        ),
    ]
