# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-02 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0077_auto_20170702_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='notes',
        ),
    ]
