# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import faker.providers.lorem.la


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0079_auto_20170703_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsettings',
            name='authority_to_act',
            field=models.TextField(blank=True, default=faker.providers.lorem.la.Provider.text, null=True, verbose_name='Authority to Act'),
        ),
        migrations.AlterField(
            model_name='contractsettings',
            name='contributor_assignment_agreement',
            field=models.TextField(blank=True, default=faker.providers.lorem.la.Provider.text, null=True, verbose_name='Contributor Assignment Agreement'),
        ),
        migrations.AlterField(
            model_name='contractsettings',
            name='parties',
            field=models.TextField(blank=True, default=faker.providers.lorem.la.Provider.text, null=True, verbose_name='Parties'),
        ),
        migrations.AlterField(
            model_name='contractsettings',
            name='payment_terms',
            field=models.TextField(blank=True, default=faker.providers.lorem.la.Provider.text, null=True, verbose_name='Payment Terms'),
        ),
        migrations.AlterField(
            model_name='contractsettings',
            name='period_of_agreement',
            field=models.TextField(blank=True, default=faker.providers.lorem.la.Provider.text, null=True, verbose_name='Period of Agreement'),
        ),
        migrations.AlterField(
            model_name='contractsettings',
            name='scope_of_work',
            field=models.TextField(blank=True, default=faker.providers.lorem.la.Provider.text, null=True, verbose_name='Scope of Work'),
        ),
    ]
