# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0082_auto_20170704_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
