# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 23:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0083_auto_20170704_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='time',
            options={'ordering': ('-updated',)},
        ),
    ]
