# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 00:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0084_auto_20170705_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={},
        ),
        migrations.AlterModelOptions(
            name='time',
            options={},
        ),
    ]
