# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0085_auto_20170705_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='app_admin',
            field=models.BooleanField(default=True),
        ),
    ]
