# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0087_auto_20170705_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
