# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0089_elevation_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='entry',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
