# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 20:00
from __future__ import unicode_literals

import datetime
from django.db import migrations
from django.utils.timezone import utc
import relativedeltafield


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0090_auto_20170706_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='flex_date',
            field=relativedeltafield.RelativeDeltaField(default=datetime.datetime(2017, 7, 9, 20, 0, 56, 927609, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
