# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 20:00
from __future__ import unicode_literals

# import datetime
from django.db import migrations
from django.utils.timezone import utc
import relativedeltafield
from dateutil.relativedelta import relativedelta


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0090_auto_20170706_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='flex_date',
            field=relativedeltafield.RelativeDeltaField(default=relativedelta(months=2,days=1,hours=6)),
            preserve_default=False,
        ),
    ]
