# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0092_auto_20170709_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name="Font Awesome Icon (without 'fa-')"),
        ),
    ]
