# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 00:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0096_client_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='flex_date',
        ),
    ]
