# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0098_auto_20170715_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
