# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0099_note_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('icon_size', models.CharField(blank=True, max_length=255, null=True)),
                ('page_size', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('dashboard_choices', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('data', 'Data'), ('invoices', 'Invoices'), ('notes', 'Notes'), ('projects', 'Projects'), ('totals', 'Totals')], max_length=35, null=True)),
                ('dashboard_order', models.CharField(blank=True, default='data, invoices, notes, projects, totals', max_length=255, null=True)),
                ('auto_hide_notes', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
