# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 22:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0100_auto_20170718_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsettings',
            name='dashboard_order',
        ),
    ]
