# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 22:56
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0101_remove_appsettings_dashboard_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='editor_choices',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ckeditor', 'CKEditor'), ('tinymce', 'tinymce')], max_length=16, null=True),
        ),
    ]
