# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0103_auto_20170718_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='editor_choices',
            field=models.CharField(blank=True, choices=[('ckeditor', 'CKEditor'), ('tinymce', 'TinyMCE')], max_length=8, null=True),
        ),
    ]
