# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 23:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0104_auto_20170718_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='priority',
        ),
    ]
