# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0105_remove_note_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Due'),
        ),
    ]
