# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0108_auto_20170720_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
