# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import faker.providers.lorem.la


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0109_appsettings_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, default=faker.providers.lorem.la.Provider.text, null=True),
        ),
    ]
