# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0112_auto_20170720_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elevation',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='zipcode',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zipcode',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
