# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0113_auto_20170720_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='file',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
