# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import faker.providers.lorem.la


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0114_auto_20170720_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, default=faker.providers.lorem.la.Provider.text, max_length=300, null=True),
        ),
    ]
