# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 21:20
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import faker.providers.lorem.la


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0115_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldBorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default=faker.providers.lorem.la.Provider.text, max_length=300)),
                ('area', models.IntegerField(blank=True, null=True)),
                ('pop2005', models.IntegerField(blank=True, null=True, verbose_name='Population 2005')),
                ('fips', models.CharField(blank=True, max_length=2, null=True, verbose_name='FIPS Code')),
                ('iso2', models.CharField(blank=True, max_length=2, null=True, verbose_name='2 Digit ISO')),
                ('iso3', models.CharField(blank=True, max_length=3, null=True, verbose_name='3 Digit ISO')),
                ('un', models.IntegerField(blank=True, null=True, verbose_name='United Nations Code')),
                ('region', models.IntegerField(blank=True, null=True, verbose_name='Region Code')),
                ('subregion', models.IntegerField(blank=True, null=True, verbose_name='Sub-Region Code')),
                ('lon', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
