# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0117_auto_20170720_1726'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='World',
            new_name='Location',
        ),
    ]
