# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0120_auto_20170726_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='is_sow',
            field=models.BooleanField(default=False, verbose_name='Use for Statement of Work?'),
        ),
    ]
