# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0122_auto_20170729_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_contact',
            field=models.BooleanField(default=False),
        ),
    ]
