# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0123_profile_is_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cog',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Cost of goods'),
        ),
    ]
