# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0124_invoice_cog'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='cog',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Cost of goods'),
        ),
    ]
