# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0127_auto_20170803_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='override_dashboard',
        ),
        migrations.AddField(
            model_name='profile',
            name='dashboard_override',
            field=models.BooleanField(default=False, verbose_name='Dashboard Override'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='dashboard_choices',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('data', 'Data'), ('invoices', 'Invoices'), ('notes', 'Notes'), ('projects', 'Projects'), ('times', 'Times'), ('totals', 'Totals')], max_length=41, null=True, verbose_name='Dashboard Choices'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dashboard_choices',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('data', 'Data'), ('invoices', 'Invoices'), ('notes', 'Notes'), ('projects', 'Projects'), ('times', 'Times'), ('totals', 'Totals')], max_length=41, null=True, verbose_name='Dashboard Choices'),
        ),
    ]
