# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20170810_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='show_hidden_notes',
            field=models.BooleanField(default=False),
        ),
    ]
