# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_auto_20170825_0642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_username',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Preferred Username'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='payment_choices',
            field=models.CharField(blank=True, choices=[('', '---'), ('check', 'Check'), ('paypal', 'PayPal'), ('wire', 'Wire')], max_length=255, null=True, verbose_name='Preferred Payment Method'),
        ),
    ]
