# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_auto_20170829_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='preferred_username',
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Preferred Username'),
        ),
    ]
