# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0032_auto_20170901_0817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimate',
            old_name='document_id',
            new_name='doc_id',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='document_type',
            new_name='doc_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='document_id',
        ),
    ]
