# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0033_auto_20170901_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='doc_type',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
