# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0046_settingscompany'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settingscompany',
            options={'verbose_name': 'Settings Company'},
        ),
    ]
