# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0051_auto_20170909_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='is_to',
            field=models.BooleanField(default=False, verbose_name='Use for Task Order?'),
        ),
    ]
